# Generated by Django 6.0.6 on 2026-10-03 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_techstack_project_created_at_alter_project_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techstack',
            options={'ordering': ['name']},
        ),
    ]
