# Generated by Django 6.0.6 on 2026-10-03 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_techstack_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technology_used',
        ),
    ]
